### ISSUE TITLE
Contains string helper fails on null value

### ISSUE THREAD

**Issue by attilah** [Handlebars-Net/Handlebars.Net.Helpers#103]
When using the `Contains` string helper and the value is `null` the underlying `string.Contains` method fails with `ArgumentNullException`. As the value can be from customer data (like in my case), I'd expect to return false instead of exception.

Suggested solution: have an optional parameter (to not be a breaking change) called `allowNulls` and if it is true then `null` value just return `false`.

> Side note: error messages around helper invocation (which can blow up easily) could be enhances to tell the helper's name, arguments, template position would be a huge help.

**Comment by attilah** [comment]
Actually after a second thought it should never fail on `null` values as the failure does not add value to the template rendering, what do you think @StefH ?

**Comment by StefH** [comment]
The official String.Contains also throws exception:

```  c#
//
        // Summary:
        //     Returns a value indicating whether a specified substring occurs within this string.
        //
        //
        // Parameters:
        //   value:
        //     The string to seek.
        //
        // Returns:
        //     true if the value parameter occurs within this string, or if value is the empty
        //     string (""); otherwise, false.
        //
        // Exceptions:
        //   T:System.ArgumentNullException:
        //     value is null.
```

So in that case, Contains string helper is the same.

**Comment by attilah** [comment]
@StefH while it is true, template authors can decide to if null is treated as empty string and when data is coming from external sources where they've no control over it, it would be useful to have control over the behavior.

But the string helpers are NOT consistent in this regard at all, almost all of them doing null or empty checks instead, and this leads to inconsistent behavior about the expected functionality IMHO.

**Comment by StefH** [comment]
You can also use String.Coalesce before you call the String.Concat
