### ISSUE TITLE
System.Diagnostic not supported in net8.0-browser

### ISSUE THREAD

**Issue by antonio8101** [Handlebars-Net/Handlebars.Net.Helpers#105]
In file `HandlebarsHelper.cs` there is a using of the `System.Diagnostics` package which is currently not supported for `net8.0-browser`.
The package is then used a t line `111` :

```csharp
Add(Path.GetDirectoryName(Process.GetCurrentProcess().MainModule?.FileName), paths);
```

This makes the use of this package impossible for Blazor Webassembly projects.

**Comment by StefH** [comment]
https://github.com/Handlebars-Net/Handlebars.Net.Helpers/pull/106
