### ISSUE TITLE
<Td> in IsMatch not working properly 

### ISSUE THREAD

**Issue by wouterDevelop** [Handlebars-Net/Handlebars.Net.Helpers#107]
I'm trying to dynamic build a html table,  But when a trying to add dynamicly a td its ignored the ismatch and showing also the <td> thats  where the conditions not met 

``` html
<table cellpadding="0" cellspacing="0" width="100%">
    <tr>
        {{notification.body.Value}} <!-- Connected -->
        {{#IsMatch "Hello" "Hello"}}yes{{else}}no{{/IsMatch}} <!-- yes -->
        {{#IsMatch "Hello" "hello"}}yes{{else}}no{{/IsMatch}} <!-- no -->
        {{#IsMatch notification.body.Value "Connected"}}Connected{{else}}Disconnected{{/IsMatch}} <!-- Connected -->
        {{#IsMatch notification.body.Value "Disconnected"}}Disconnected{{else}}Connected{{/IsMatch}} <!-- Connected -->

        <!-- Dynamically add a <td> based on the value of notification.body.Value -->
        {{#IsMatch notification.body.Value "Connected"}}<td>TEST1</td>{{else}}{{/IsMatch}} <!-- Shown -->
        {{#IsMatch notification.body.Value "Disconnected"}}<td>TEST2</td>{{else}}{{/IsMatch}} <!-- Should not be shown -->

        <!-- Avoid placing non-table elements inside <tr> (like <h1>) unless supported -->
        {{#IsMatch notification.body.Value "Disconnected"}}<h1>TEST2</h1>{{else}}{{/IsMatch}} <!-- Not showing -->
    </tr>
</table>
```

**Comment by StefH** [comment]
@wouterDevelop 
1. Can you show you **notification** data?
2. And what happens if you use `Equal` instead of `IsMatch` ?

**Comment by wouterDevelop** [comment]
Thanks you stef, 

I tried is also with Equal  


        {{#String.Equal "foo" "foo"}}
        <td>yes</td>
        {{else}}
        <td>no</td>
        {{/String.Equal}}
        
         same result. 
         
  The notification data is a object format but also withouth a data input u have the same result.

**Comment by StefH** [comment]
Can you show full code? Or example project?

Because I cannot yet reproduce the error, see https://github.com/Handlebars-Net/Handlebars.Net.Helpers/pull/108

**Comment by wouterDevelop** [comment]
The issue is solved. The problem was in my code, where I accidentally placed two handlebars next to each other.
