### ISSUE TITLE
Consider moving repo under Handlebars-Net org?

### ISSUE THREAD

**Issue by zjklee** [Handlebars-Net/Handlebars.Net.Helpers#14]
Hi @StefH 

Would you consider moving the repo under [Handlebars-Net](https://github.com/Handlebars-Net) organisation? This can provide better visibility as everything related to Handlebars.Net would be hosted under single roof.

**Comment by StefH** [comment]
Hello @zjklee, I think this is indeed a good idea.

However I would like to keep full admin rights on the repository because I also use Azure Pipelines for CI and build nuget packages.

**Comment by zjklee** [comment]
@StefH 
Sure, that's definitely a way to go. That's your work and you definitely should keep the whole admin access.

**Comment by zjklee** [comment]
@StefH 
Now as a member of the organization you can transfer the repo. Once it’s transferred I’d restore your full access to it.

**Comment by StefH** [comment]
Repository is moved to this organization. Can you restore admin access?

**Comment by zjklee** [comment]
@StefH
I’ve granted you Admin role back.

**Comment by StefH** [comment]
@zjklee 
Thanks.

Can you also approve my request for azure pipelines authentication/access?

**Comment by zjklee** [comment]
@StefH Done

**Comment by StefH** [comment]
Thanks.

Next step would be to investigate if some helpers from here (https://github.com/WireMock-Net/WireMock.Net/tree/master/src/WireMock.Net/Transformers) can be moved to some new Helper projects.

For example:
HandlebarsXPath --> Handlebars.Net.Helpers.XPath

**Comment by zjklee** [comment]
I'd say you can go even further and host each helper category in a separate NuGet package and use this repo as a mono-repo.
