### ISSUE TITLE
System.ArgumentException: 'Object of type 'System.Int32' cannot be converted to type 'System.String'.'

### ISSUE THREAD

**Issue by Zulu-Inuoe** [Handlebars-Net/Handlebars.Net.Helpers#21]
Hey all,

I noticed the following interesting behaviour:

```csharp
var handlebars = Handlebars.Create();
HandlebarsHelpers.Register(handlebars);
var expansion = handlebars.Compile("{{String.Lowercase Foo}}")(new Dictionary<string, string> { ["Foo"] = "42" });
```
Throws an exception:
```
System.ArgumentException: 'Object of type 'System.Int32' cannot be converted to type 'System.String'.'
```
It seems the string "42" is somehow being coerced to an integer, prior to being passed to String.Lowercase and failing to conver to a string.

1. Why would this automagically coerce to an int32 ?
2. Is there a strict reason why we wouldn't allow an int32 to be coerced into a string when using the String helpers? If not, mayhaps consider some sort of 'ToString()'  expression?

Thanks!

**Comment by StefH** [comment]
@Zulu-Inuoe I see your point, I'll fix this.

**Comment by StefH** [comment]
A new version will be released soon.

**Comment by Zulu-Inuoe** [comment]
@StefH Thanks for looking into this so quickly! I tested the new changes as it works as expected. My only concern was breaking the Math handlers, but they already accept `object` so it all works out.

Thank you!
