### ISSUE TITLE
Regex.IsMatch alternative to preserve context?

### ISSUE THREAD

**Issue by Zulu-Inuoe** [Handlebars-Net/Handlebars.Net.Helpers#25]
Hello!

I stumbled on this interesting behaviour with `Regex.IsMatch`:

```csharp
var handlebars = Handlebars.Create();
HandlebarsHelpers.Register(handlebars, opt => { opt.CustomHelperPaths = new string[0]; });
var context = new Dictionary<string, object>()
{
    ["Attributes"] = "visible",
    ["Value"] = "SomeString"
};

var expansion = handlebars.Compile("{{#Regex.IsMatch Attributes 'visible'}}{{Value}}{{/Regex.IsMatch}}")(context);
```

This gets me an empty string. I tried again, using `{{.}}` rather than `{{Value}}` I got the string "True"

So it looks like `Regex.IsMatch` will set the Handlebars context to the match result., so if I want to get at the previous context I have to do eg `{{../Value}}`, however this seems quite awkward and surprising. It definitely does not behave like `#if` and `#unless` do.

Now, "fixing" this to not alter context is no doubt going to break somebody's template out there since it's been this way [since it was introduced](https://github.com/Handlebars-Net/Handlebars.Net.Helpers/commit/9dfc3c0361b57ac7cca8ae15ed95d39d0ad6688a)

But what do you think @StefH of having a variant of `IsMatch` with a different name, which is exactly like `IsMatch`, but preserves the current context?

**Comment by StefH** [comment]
https://github.com/Handlebars-Net/Handlebars.Net.Helpers/pull/26

**Comment by StefH** [comment]
@Zulu-Inuoe 
I think you need to use the **"#if"** code:

``` c#
            // Arrange
            var template = "{{#if (#Regex.IsMatch Attributes 'visible')}}{{Value}}{{/if}}";
            var context = new Dictionary<string, object>()
            {
                ["Attributes"] = "visible",
                ["Value"] = "SomeString"
            };
            var action = _handlebarsContext.Compile(template);

            // Act
            var result = action(context);

            // Assert
            result.Should().Be("SomeString");
```

**Comment by Zulu-Inuoe** [comment]
@StefH I see, that makes sense. I hadn't considered Handlebars subexpressions.

Thank you!
