### ISSUE TITLE
Regex.IsMatch broken with ignore case

### ISSUE THREAD

**Issue by Zulu-Inuoe** [Handlebars-Net/Handlebars.Net.Helpers#27]
Maybe this is a mistake on my side, but it looks like when you supply an 'i' flag to Regex.IsMatch, it always matches true (from what I can tell):

This **works** aka results in an empty string because "bar" does not match the regex "foo":
```csharp
            var result = h.Compile(@"{{#Regex.IsMatch thing 'foo'}}Yes{{/Regex.IsMatch}}")(new
            {
                thing = "bar"
            }) ;
```

This **breaks** aka results in "Yes", even though "bar" does not match the regex "foo":
```csharp
            var result = h.Compile(@"{{#Regex.IsMatch thing 'foo' 'i'}}Yes{{/Regex.IsMatch}}")(new
            {
                thing = "bar"
            }) ;
```

**Comment by StefH** [comment]
@Zulu-Inuoe 
What happens if you use `"` instead of `'`?

**Comment by Zulu-Inuoe** [comment]
@StefH I tried
```csharp
            var result = h.Compile(@"{{#Regex.IsMatch thing ""foo"" ""i""}}Yes{{/Regex.IsMatch}}")(new
            {
                thing = "bar"
            }) ;
```
and am still seeing "Yes" rather than expected ""

**Comment by StefH** [comment]
I've found the issue. A new version will be released shortly.
