### ISSUE TITLE
Question - Math comparison?

### ISSUE THREAD

**Issue by Zulu-Inuoe** [Handlebars-Net/Handlebars.Net.Helpers#29]
Hi, this is more of a question/maybe feature request.

Do you think it'd be reasonable to implement some sort of math-based comparisons (<, <=, ==, >=, >) in the math category?

I received a requirement to apply styling on elements on a list past a certain index eg

```handlebars
{{#each Items}}
<div class="{{#if (Math.Greater @index 5)}}hide{{/if}}">
 ...
</div>
{{/each}}
```

I'm wondering if this sort of thing might be useful in a general case, given there's already other useful math functions.

**Comment by Zulu-Inuoe** [comment]
And for the record, one can technically achieve this right now with a little math trickery & the fact that 0 is falsy:
```handlebars
<div class="{{#if (Math.Max 0 (Math.Sign (Math.Subtract @index 5)))}}hide{{/if}}">
</div>
```
But that might be a bit too clever.

**Comment by StefH** [comment]
Maybe instead of the Math helpers, use the 'Handlebars.Net.Helpers.DynamicLinq' ?

**Comment by StefH** [comment]
@Zulu-Inuoe , a new NuGet will be released shortly.

With:
Equal,
NotEqual,
GreaterThan,
GreaterThanEqual,
LessThan,
LessThanEqual

**Comment by StefH** [comment]
#30

**Comment by Zulu-Inuoe** [comment]
Sorry in being late responding to this. Thank you so much!

We pulled the latest version and the math puzzle from before is now gone 😄
