### ISSUE TITLE
Random number generation isn't very random

### ISSUE THREAD

**Issue by johngallardo** [Handlebars-Net/Handlebars.Net.Helpers#41]
Consider a template spec:
```
{
    "time": "{{Now}}",
    "temperature": {{Random Type="Integer" Min=20 Max=100}}
}
```

And generation of data in a loop:
```
            var handlebarsContext = HandlebarsDotNet.Handlebars.Create();
            HandlebarsHelpers.Register(handlebarsContext, options => { options.UseCategoryPrefix = false; });

            var template = handlebarsContext.Compile(spec);
            for (int i = 0; i < 100; i++)
            {
                var result = template(new { });
                Console.WriteLine(result);
            }
```

The randomly generated data rarely varies. Seems the root cause here is the usage of RandomDataGenerator creates a new Randomizer object on every iteration of generation. The result is not much randomness, as the different Randomizer's all seem to be initialized with a seed that is based on system clock.

**Comment by StefH** [comment]
@johngallardo 
This issue is solved by https://github.com/StefH/RandomDataGenerator/pull/26

A new version from Handlebars.Net.Helpers will be released shortly.
