### ISSUE TITLE
Consider adding Handlebars-Net NuGet org as additional package owner

### ISSUE THREAD

**Issue by zjklee** [Handlebars-Net/Handlebars.Net.Helpers#44]
Hello @StefH 

Recently I've added you as [Handlebars-Net NuGet org](https://www.nuget.org/profiles/Handlebars-Net) administrator so that you can manage packages through the org. Consider adding the org as additional package owner.
Why now? Recently we got "Reserved prefix" for "Handlebars.Net" name and prefix ownership is assigned to the org.

**Comment by StefH** [comment]
@zjklee 
Can you check if the NuGet permissions are correctly defined for you?

**Comment by zjklee** [comment]
@StefH, unfortunately, I'm not sure what you're asking about. I see you joined the org, but org is still not mentioned as one of the packages owners.

**Comment by StefH** [comment]
@zjklee 

I see this:
![image](https://user-images.githubusercontent.com/249938/147537467-82370210-ea46-4ba4-be8e-9a4243a1b060.png)

And I see this:
![image](https://user-images.githubusercontent.com/249938/147537552-de64bad0-5f54-4c59-9e0f-be55b76e8d21.png)



---

I did send a new email to NuGet account support to add you also as an owner to the prefix.

**Comment by zjklee** [comment]
@StefH,
Probably you've misunderstood me.
The org owns `Handlebars.Net` prefix and I do have access to it.
I was talking about adding the org as an additional package owner to packages owned by you: `Handlebars.Net.Helpers.*`. This way prefix will be applied to them.

**Comment by StefH** [comment]
I've sent email to NuGet, and I get this response:
```
To qualify for your ID prefix reservation, please consider the following actions:

  • The rexm account needs to have 2FA enabled before we can make changes to the reservation owned by Handlebars-Net (all members of an organization need 2FA, and rexm is a member of Handlebars-Net).

  • The rexm account needs to have 2FA enabled before we can add it as an owner to the prefix reservation.
```
@rexm, can you please enable 2FA on your GitHub account?

**Comment by zjklee** [comment]
@StefH, we already have ID prefix reserved.
In order to get it applied to `Handlebars.Net.Helpers*` packages you need to add Handlebars-Net org as an additional packages owner.

**Comment by rexm** [comment]
That’s odd. I’ve had 2FA for years (and also a personal thing to reveal to someone else!) - try what @zjklee suggested.

**Comment by StefH** [comment]
@rexm and @zjklee 
I did send an email some week(s) ago to NuGet support, however no reply yet (I think).

But can you check again if the permissions are correct for you now?

**Comment by zjklee** [comment]
Hello @StefH 
It's not about our permissions.
It's about adding Handlebars-Net NuGet org as a second owner to the package (on the NuGet portal).
This way packages will get "verified" badge as the prefix is owned by Handlebars-Net org.
You do not need any help from NuGet support. You, as package owner, can update owners yourself.

**Comment by StefH** [comment]
@zjklee 
As a test, I did add `Handlebars-Net` as owner to:
![image](https://user-images.githubusercontent.com/249938/151224358-8a70a52b-4cb6-4a75-9d13-d2693127645b.png)


Note that only the main package is verified it seems? Or will that change once you accept as owner?

**Comment by zjklee** [comment]
Oh, I've just noticed that you've added org as an owner to `Handlebars.Net.Helpers`. Yes, you need to do the same with other packages.
I do not need to accept anything as you're the org admin as well 😉

**Comment by StefH** [comment]
All my packages are updated.
