### ISSUE TITLE
[Question] String.Equals is strangely missing

### ISSUE THREAD

**Issue by tinytownsoftware** [Handlebars-Net/Handlebars.Net.Helpers#46]
While I can use Regex.IsMatch to test for string equality, it is cumbersome. Looking through the source, String.Equals would be very easy to add. Any plans on doing so? Alternately I can do it and make a PR.

**Comment by StefH** [comment]
You can add this in a PR.

(also add a unit test)

**Comment by tinytownsoftware** [comment]
https://github.com/Handlebars-Net/Handlebars.Net.Helpers/pull/47

**Comment by StefH** [comment]
@tinytownsoftware 
Thanks for the PR.
