### ISSUE TITLE
Update to the latest Handlebars.Net version

### ISSUE THREAD

**Issue by zjklee** [Handlebars-Net/Handlebars.Net.Helpers#50]
Hello @StefH ,

I'd really appreciate if you can update packages to the latest Handlebars.Net version. Unfortunately, `>=` version condition does not work for full framework targets.

**Comment by StefH** [comment]
Sure.

I will do this end of the week.

**Comment by StefH** [comment]
https://github.com/Handlebars-Net/Handlebars.Net.Helpers/pull/51
