### ISSUE TITLE
Add examples of using the String.Split helper in a #each expression

### ISSUE THREAD

**Issue by SeanFarrow** [Handlebars-Net/Handlebars.Net.Helpers#53]
I am trying to use the String.Split helper in an #each expression, but can't seem to find the correct syntax.

Does anyone have any examples?

Thanks,
Sean.

**Comment by kspearrin** [comment]
I can't seem to get this to work either. Example:

Template
```
{{#each (String.Split 'a;b;c' ';')}}
{{this}}
{{/each}}
```

Result

```
13
```

**Comment by kspearrin** [comment]
@StefH Yes, I can get `String.Split` to work on its own, but when pairing the result with `#each` to iterate over the array, I get the weird behavior shown above, showing the length of the array.

**Comment by StefH** [comment]
Currently, the result from that string.split is a json-array. Not a real object array which can be used in each-loop.

I can't remember why I build this code to behave like this... Maybe a different usecase....

I need to think on this...

**Comment by kspearrin** [comment]
In the meantime, I was able to fix this by just overloading the exiting String.Split helper with my own custom one:

                context.RegisterHelper("String.Split", (context, arguments) =>
                {
                    var value = arguments[0] as string;
                    var separator = arguments[1] as string;
                    return value.Split(separator);
                });

**Comment by StefH** [comment]
https://github.com/Handlebars-Net/Handlebars.Net.Helpers/pull/57

**Comment by StefH** [comment]
@kspearrin 
Preview version `2.3.8-ci-16673.` should solve this. Can you test ?

(https://github.com/Handlebars-Net/Handlebars.Net.Helpers/wiki/MyGet)

**Comment by kspearrin** [comment]
@StefH Confirmed that it works.
