### ISSUE TITLE
Add String.Coalesce

### ISSUE THREAD

**Issue by kspearrin** [Handlebars-Net/Handlebars.Net.Helpers#60]
It would be nice to have a helper that coalesces to find the first non-null/empty/whitespace value. I created this helper to serve my needs (see below). I would submit a PR for this, but I am unsure how to add infinite argument helpers, given your existing helper examples are all finite.

Is there interest in such a helper for this library?

```c#
context.RegisterHelper("String.Coalesce", (context, arguments) =>
{
    foreach (var arg in arguments)
    {
        if (arg != null)
        {
            if (arg is string s)
            {
                if (!string.IsNullOrWhiteSpace(s))
                {
                    return arg;
                }
            }
            else
            {
                return arg;
            }
        }
    }
    return null;
});
```

```hbs
Result: {{String.Coalesce "", " ", "", "a", "b", "", "c"}}
```

```
Result: a
```

**Comment by StefH** [comment]
Technically this should be possible. I'll take a look.

**Comment by StefH** [comment]
https://github.com/Handlebars-Net/Handlebars.Net.Helpers/pull/61

**Comment by StefH** [comment]
@kspearrin 
You can try preview `2.3.8-ci-16687`

**Comment by StefH** [comment]
@kspearrin 
if this fix is ok, then i can create a new nuget which includes your pr + this one

**Comment by kspearrin** [comment]
@StefH Tested and looks good. Thanks.
