### ISSUE TITLE
BSOD when using calling HandlebarsHelpers.Register in a C# WinForms project with MS Webview2

### ISSUE THREAD

**Issue by cernealax** [Handlebars-Net/Handlebars.Net.Helpers#69]
Prerequisites:

1. Winforms project
2. Nuget package Microsoft.Web.WebView2@1.0.1587.40 (I tried with several versions with the same outcome)
3. Nuget package Handlebars.Net@2.1.2
4. Nuget package Handlebars.Net.Helpers@2.3.11 (I tried with several versions with the same outcome)

Steps to reproduce
Somewhere in the app have these lines of code:  
```
  var handlebarsContext = Handlebars.Create();
  HandlebarsHelpers.Register(handlebarsContext);
```

Result:
BSOD - driver overran stack buffer

Notes: 

1. same code but in a Winforms project without Microsoft.Web.WebView2 runs ok. 
2. same code but in a Console project runs ok 
3. attached a sample project.
[bsod.zip](https://github.com/Handlebars-Net/Handlebars.Net.Helpers/files/10764625/bsod.zip)

**Comment by StefH** [comment]
@cernealax 
Sorry. I cannot reproduce your problem. Are you sure if there are no other strange things and settings on your visual studio or pc?
