### ISSUE TITLE
Handlebars.Net.Helpers.Xpath v2.4.1.4 is detected as a threat (Trojan.MSILHeracles)

### ISSUE THREAD

**Issue by JordanGottardo** [Handlebars-Net/Handlebars.Net.Helpers#89]
Handlebars.Net.Helpers.Xpath v2.4.1.4 is detected as a threat by various threat detection softwares (by virustotal.com)

Steps to reproduce:

1. install Handlebars.Net.Helpers.Xpath v2.4.1.4 from nuget
2. upload %UserProfile%\.nuget\packages\handlebars.net.helpers.xpath\2.4.1.4\lib\netstandard1.3\HandlebarsDotNet.Helpers.XPath.dll to virustotal.com
=>
Multiple vendors are detecting it as a threat
![image](https://github.com/Handlebars-Net/Handlebars.Net.Helpers/assets/15140122/0d992ed1-bbb9-4d84-ab04-8f9534ec2a80)

This seems to happen only for the netstandard1.3 dll.
Is this a false positive?

**Comment by StefH** [comment]
I think it's a false positive indeed
