### ISSUE TITLE
Helper with name "Not"  not found 

### ISSUE THREAD

**Issue by chandraarora** [Handlebars-Net/Handlebars.Net.Helpers#98]
Hi 

It seems to me that i am doing a syntax or it is able able to find the help "not". could you please the below code and if am using not is right way.
``` c#
using HandlebarsDotNet;
using HandlebarsDotNet.Helpers;

namespace test.Handlebars
{
    internal class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Hello, World!");

            string source =
@"{
    ""testFilter"": {
     
      ""enum"": [ {{#each data}}  {{#if ( not @first) }}  }} , ""{{this}}"" {{else}} ""{{this}}""{{/if}} {{/each}}],
     
  
}";

            var handlebarsContext = HandlebarsDotNet.Handlebars.Create();
            HandlebarsHelpers.Register(handlebarsContext);
            
            var template = handlebarsContext.Compile(source);
            var data1 = new 
            {
                data = new[] { "text1", "text2", "text3" }
                
            };

 

            var result = template(data1);

            

        }
    }
}
 ```

**Comment by StefH** [comment]
Maybe try this:

``` handlebars
{{#each data}}
  {{#if @first}}
    "{{this}}"
  {{else}}
    , "{{this}}"
  {{/if}}
{{/each}}

```

**Comment by chandraarora** [comment]
Thank you, I saw in the code there is not operator , would it be possible to use it, just for my knowledge

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by StefH** [comment]
It is supported.

See
https://github.com/Handlebars-Net/Handlebars.Net.Helpers/blob/master/test/Handlebars.Net.Helpers.Tests/Templates/BooleanHelpersTemplateTests.cs

use `Boolean.Not` or set the config to : https://github.com/Handlebars-Net/Handlebars.Net.Helpers?tab=readme-ov-file#without-a-prefix

**Comment by chandraarora** [comment]
Thank you it worked
